blueprint:
    name: AWTRIX Weather
    description: "This blueprint will show the weather on a AWTRIX display."
    domain: automation
    source_url: https://raw.githubusercontent.com/mdonath/ha-blueprints/main/awtrix_weather.yaml

    homeassistant:
        min_version: "2024.6.0"

    input:
        awtrix:
            name: AWTRIX Device
            description: Select the Awtrix light device
            selector:
            device:
                filter:
                    -   integration: mqtt
                        manufacturer: Blueforcer
                        model: AWTRIX 3
                multiple: true
        weather_entity:
            name: Weather entity
            description: Set the entity for weather information
            selector:
            entity:
                filter:
                - domain: weather
                multiple: false

mode: single
variables:
    device_ids: !input awtrix
    app_id: "weather"
    devices_topics: |
        {%- macro get_device_topic(device_id) %}
          {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
        {%- endmacro %}
        {%- set ns = namespace(devices=[]) %}
        {%- for device_id in device_ids %}
          {%- set device=get_device_topic(device_id)|replace(' ','') %}
          {% set ns.devices = ns.devices + [ device ~ '/custom/' + app_id] %}
        {%- endfor %}
        {{ ns.devices }}

    weather_var: !input weather_entity
    weather_icon: "w-{{states(weather_var)}}"
    weather_temperature: "{{state_attr(weather_var, 'temperature')}}"
    weather_temperature_unit: "{{state_attr(weather_var, 'temperature_unit')}}"

    payload: '{"icon":"{{weather_icon}}", "text":"{{ weather_temperature }}{{ weather_temperature_unit }}"}'

triggers:
    -   trigger: time_pattern
        minutes: /1

#condition:

actions:
    sequence:
    -   repeat:
        for_each: "{{ devices_topics }}"
        sequence:
            -   action: mqtt.publish
                data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: "{{ payload }}"
