blueprint:
  name: Calendar Switch Access Profile
  description: Switch on or off according to Calendar State
  domain: automation
  source_url: https://raw.githubusercontent.com/mdonath/ha-blueprints/main/calendar_switch.yaml
  input:
    input_calendar:
      name: Calendar
      description: The calendar that defines periods of on/off
      selector:
        entity:
          domain: calendar
    target_switch:
      name: Target Switch
      description: The switch that should follow the schedule in the calendar
      selector:
        entity:
          integration: fritzbox_tools
          domain: switch


trigger:
  - platform: state
    entity_id: !input input_calendar

condition: []

actions:
  - action: 'switch.turn_{{trigger.to_state.state}}'
    target:
      entity_id: !input target_switch

mode: single
